# Generated by Django 4.2.6 on 2023-11-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('CATDESC', models.CharField(blank=True, max_length=100, null=True)),
                ('CATIMAGE', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
    ]
