# Generated by Django 4.2.7 on 2024-01-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_auto_20231228_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prodcutdb',
            name='PROPRICE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prodcutdb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
