# Generated by Django 4.2.6 on 2023-12-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('EMAIL', models.CharField(blank=True, max_length=100, null=True)),
                ('MESSAGE', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
